stages:
  data_preprocessing:
    cmd: python scripts/data_preprocessing.py --store data/raw/store.csv --train data/raw/train.csv --output data/preprocessed/store_preprocessed.csv
    deps:
      - scripts/data_preprocessing.py
      - data/raw/store.csv
      - data/raw/train.csv
    outs:
      - data/preprocessed/store_preprocessed.csv

  # model_training:
  #   cmd:
  #     python scripts/train_model.py --input data/preprocessed/store_preprocessed.csv
  #     --output model.pkl
  #   deps:
  #     - scripts/train_model.py
  #     - data/preprocessed/store_preprocessed.csv
  #   outs:
  #     - model.pkl
  #   params:
  #     - train.model_params.max_iter
